name: Checkout Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: pull_request_target
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checkout"
